run:
  deadline: 5m

issues:
  exclude-dirs:
    - hooks
    - scripts

linters:
  disable-all: true
  enable:
   - errcheck
   - goconst
   - gocyclo
   - goimports
   - gosec
   - govet
   - ineffassign
   - misspell
   - revive
   - unconvert
   - unparam
   - unused

